### ISSUE TITLE
error running hook: exit status 3

### ISSUE THREAD

**Issue by davidshen84** [NVIDIA/nvidia-container-toolkit#14]
Hi,

I build the nvidia-docker and related repositories myself on my Gentoo system, and I managed to get an older version, nvidia-docker v2.6.0, work. Now I am trying to upgrade nvidia-docker and related packages to match the latest.

I got all the packages building, but when I try `nvidia-smi` in a container, I got the following error.

```
Feb 13 11:11:05 gentoo dockerd[1575]: time="2022-02-13T11:11:05.375450808+11:00" level=error msg="Handler for POST /v1.41/containers/31dc8c5a195f638702aad6607626cd0e4dcc985fed76eda087a99d5750bdb97b/start returned error: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 3, stdout: , stderr: time=\"2022-02-13T11:11:05+11:00\" level=error msg=\"No help topic for 'prestart'\\n\": unknown"
Fe
```

Here's the log from the `/var/log/nvidia-container-runtime.log` file:

```
2022/02/13 11:17:07 Using bundle directory: /var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/27c7f03acb934dfbd29b2e68504d7a0efe5267631f197befca88085736b62a1b
2022/02/13 11:17:07 Using OCI specification file path: /var/run/docker/containerd/daemon/io.containerd.runtime.v2.task/moby/27c7f03acb934dfbd29b2e68504d7a0efe5267631f197befca88085736b62a1b/config.json
2022/02/13 11:17:07 Looking for runtime binary 'docker-runc'
2022/02/13 11:17:07 Found runtime binary '/usr/bin/docker-runc'
2022/02/13 11:17:07 Running /usr/bin/nvidia-container-runtime

2022/02/13 11:17:07 'create' command detected; modification required
2022/02/13 11:17:07 prestart hook path: /usr/bin/nvidia-container-runtime-hook

2022/02/13 11:17:07 Forwarding command to runtime
2022/02/13 11:17:07 Using bundle directory:
2022/02/13 11:17:07 Using OCI specification file path: config.json
2022/02/13 11:17:07 Looking for runtime binary 'docker-runc'
2022/02/13 11:17:07 Found runtime binary '/usr/bin/docker-runc'
2022/02/13 11:17:07 Running /usr/bin/nvidia-container-runtime-hook

2022/02/13 11:17:07 No modification required
2022/02/13 11:17:07 Forwarding command to runtime
```

### Host

- Linux gentoo 5.15.16-gentoo-x86_64 #1 SMP Sun Feb 6 13:49:08 AEDT 2022 x86_64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz GenuineIntel GNU/Linux
- nvidia-drivers-470.103.01
- no cuda installed

## Container

- official nvidia/cuda-11.5.1-runtime-ubuntu20.04

I wonder if there's any way to make the toolkit emit more debug information.

Thanks.

**Comment by elezar** [comment]
Hi @davidshen84. The error message you're seeing seems to indicate an error with how the hooks are set up on your system. Could you describe how your system is configured and how the container is being launched? Specifically how the OCI hooks are configured.

With regards to:
> I wonder if there's any way to make the toolkit emit more debug information.

No, unfortunately not at this stage.

**Comment by davidshen84** [comment]
Hi @elezar ,

In the build folder, I found these two OCI related files:

- oci-nvidia-hook
- oci-ncidia-hook.json

But I use the files in `packaging/debian` as a reference to create the installation scripts for Gentoo, and these two OCI files are not mentioned in the Debian installation script. So I omitted them in my installation script.

As you mentioned, I checked the scripts in `packaging/rpm` and I found they are referenced.

I don't know much about Debian and rpm installation scripts. Will the Debian script automatically install/configure those OCI files without even mentioning them?

Would you describe briefly where should I put those OCI files and how should I configure the nvidia-container-toolkit to use it?

Thanks.

**Comment by davidshen84** [comment]
Hi @elezar ,

I checked the previous version's installation file, and there are no OCI files at all.

Just to clarify, when you say "OCI hooks", are you referring to this script file, https://github.com/NVIDIA/nvidia-container-toolkit/blob/master/oci-nvidia-hook?

Thanks.

**Comment by klueska** [comment]
He’s talking about the hooks that are part of the OCI spec into which path of the nvidia-contain-toolkit is pit so that runC can call out to it at the appropriate time. There are several ways this happens depending on which container runtime you are using.

With crio-o, the files you referenced do this because crio-o has machinery to look for these files and patch the OCI spec appropriately. With docker > 19.03, passing the —gpus flag will do this patching automatically. With docker < 19.03 (or any other runtime), you need the nvidia-container-runtime installed (and configured as the default “lower-level” runtime) to act as a shim between docker and runC to do this injection for you.

Based on your error message it looks like all of this is actually working OK, except it seems some outdated hook is being called. Can you remove any reference to a file called “nvidia-container-runtime-hook” that you may have installed on your system, and try building things again.

This file was replaced in newer versions by a file called “nvidia-container-toolkit” (with a symlink created for nvidia-container-runtime-hook to point to it for backwards compatibility).

**Comment by davidshen84** [comment]
Hi @klueska ,

> This file was replaced in newer versions by a file called “nvidia-container-toolkit” (with a symlink created for nvidia-container-runtime-hook to point to it for backwards compatibility).

My editor's autocomplete *helped* me creating a link from `nvidia-container-runtime-hook` to `nvidia-container-runtime`...

Thank you so much!
