### ISSUE TITLE
Modifying NVIDIA_VISIBLE_DEVICES Before Submitting the Request to Containerd Results to Inconsistent GPU Assignment

### ISSUE THREAD

**Issue by ZeroExistence** [NVIDIA/nvidia-container-toolkit#27]
Hello, I am kind of working into a software that modified the assigned GPUs when the kubelet sent the container create request to containerd. 

I tried doing the modification of NVIDIA_VISIBLE_DEVICES between kubelet and containerd connection. But I noticed that when we modify the NVIDIA_VISIBLE_DEVICES with other GPU UUIDs, the pod was created with both the initially assigned GPUs, and the newly assigned GPUs.

1. Original kubelet -> containerd request has `NVIDIA_VISIBLE_DEVICES=GPU-UUID1`. I assume this value was automatically set by the NVIDIA container-toolkit, because we haven't set the NVIDIA_VISIBLE_DEVICES in Kubernetes pod level.
2. Modify the variable to use the preferred GPU instead -> `NVIDIA_VISIBLE_DEVICES=GPU-UUID2`. After modifying it, pass the request to the containerd socket.
3. When the pod is created, the pod has access to both GPU devices. When I checked the environment variable of the pod, the `NVIDIA_VISIBLE_DEVICES=GPU-UUID2` variable is the only one set.

Do you have and idea on this kind of behavior?

I haven't reviewed this code base, but how does container-toolkit kind of specify the GPUs to be assigned in a pod? I thought that when we change the UUID specified in the `NVIDIA_VISIBLE_DEVICES`, the runtime respect this value and proceed in using that GPU.

I am also considering, should we also forward the NVIDIA container toolkit communication on our proxy software?
```
    Environment:
      RUNTIME_ARGS:               --socket /runtime/sock-dir/containerd.sock --config /runtime/config-dir/config.toml
      CONTAINERD_CONFIG:          /etc/containerd/config.toml
      CONTAINERD_SOCKET:          /run/containerd/containerd.sock
```

This is a duplicated post here: https://gitlab.com/nvidia/container-toolkit/container-toolkit/-/issues/1. Feel free to disregard/close one of the duplicated post if needed.

**Comment by klueska** [comment]
A few questions:
1. How many total GPUs do you have on your system?
2. What container image are you running?
3. Are you running your pod as privileged?
4. Is there a reason to set `NVIDIA_VISIBLE_DEVICES` directly instead of relying on the device plugin?

In general, setting `NVIDIA_VISIBLE_DEVICES` directly in a pod spec is unsupported and should be avoided. That said, the way in which you are using it, should work, so I'm guessing you may be running your pod as privileged, in which case you will have access to all GPUs regardless of this setting.

**Comment by klueska** [comment]
Depending on what you are trying to do, this may be of interest to you:
https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit?disco=AAAAXeadCNY

**Comment by ZeroExistence** [comment]
Here's the requested information.

> How many total GPUs do you have on your system?

We use 8 GPUs per node. We are using various GPU types on our systems (ex. Pascal, Volta, Ampere GPUS)

> What container image are you running?

We are using customized NVIDIA CUDA 11+ images with ubuntu20.04,  but the CUDA/CUDNN installation is almost the same with the NVIDIA CUDA images.

> Are you running your pod as privileged?

No. We are using a normal pod, without restrictions and default privileges.

> Is there a reason to set `NVIDIA_VISIBLE_DEVICES` directly instead of relying on the device plugin?

We are kind of doing optimized GPU assignments in our pods, based on some metrics.

Just an additional information, our Kubernetes cluster has an NVIDIA gpu-operator deployed (nvidia-container-toolkit-daemonset, nvidia-device-plugin-daemonset)

> That said, the way in which you are using it, should work, so I'm guessing you may be running your pod as privileged, in which case you will have access to all GPUs regardless of this setting.

Yeah, I am also assuming that this should work, since on our logging, we confirmed that the initial GPUs and the newly assigned GPUs are assigned correctly with the oci runtime spec. So I'm checking if container-toolkit is still doing some hook works somewhere when the containerd received the modified pod create request.

Assumed Communication Diagram:
K8S API -> kubelet (with specified NVIDIA env, by toolkit?) -> custom proxy (where NVIDIA env happens) -> containerd socket

So I'm not sure if I'm still missing something on this assumed communication diagram somewhere.

> Also, depending on what you are trying to do, this may be of interest to you:
> https://docs.google.com/document/d/1zy0key-EL6JH50MZgwg96RPYxxXXnVUdxLZwGiyqLd8/edit?disco=AAAAXeadCNY

Thank you for this reference document. I was able to check it too, and still reviewing if this can be applied or something with our K8s-containerd setup.

**Comment by klueska** [comment]
I don't quite follow your assumed communication diagram, but in general the flow is the following (assuming you are using the plugin, with requests to `nvidia.com/gpu=<count>` in your pod spec):

1. Device plugin registers set of available devices with kubelet
1. Pod gets scheduled to node
1. kubelet looks at request for `nvidia.com/gpu=<count>` and allocates GPUs from the list of GPUs received from plugin
1. kubelet calls out to device plugin to ask it what (limited) CRI options it would like to set for the container, based on the list of GPUs it has decided to allocate
1. Device plugin sets the `NVIDIA_VISIBLE_DEVICES` envvar as a CRI option, listing the set of GPUs allocated by the kubelet. If you happen to have this envvar set in your pod spec or have it pre-set in the container image, the setting from the device plugin will overwrite this.
1. kubelet triggers creation of the container passing it the CRI options set by the plugin (and other components)
1. The container runtime (containerd in your case) creates an OCI runtime spec specifying the full set of capabilities that the container should have (including taking into account the CRI options passed to it by the kubelet)
1. The container runtime then calls out to a "low-level" runtime, passing it the OCI runtime spec it just created
1.  In your case (and for anyone running with GPU support in containerd), this "low-level" runtime is configured as the `nvidia-container-runtime`, which is a thin wrapper around `runC` that does nothing more than *further* modify the OCI runtime spec and then shell out `runC` under the hood. The modification made is to inject a single `prestart` hook for an executable called the `nvidia-container-runtime-hook`.
1. `runC` then starts the container, calling the `nvidia-container-runtime-hook` at the appropriate time during this process
1. The `nvidia-container-runtime-hook` then looks at the `NVIDIA_VISIBLE_DEVICES` envvar that is set and triggers injection of the GPUs listed in it.

In your case of bypassing the plugin by *not* using requests for `nvidia.com/gpu=<count>` and instead setting the `NVIDIA_VISIBLE_DEVICES` envvar directly, the same process would be followed, but starting with (6). That is to say that the kubelet will not call out to the plugin in any way, and instead just immediately trigger containerd to start your container (using the settings for the `NVIDIA_VISIBLE_DEVICES` envvar from your podspec / container image instead of from the plugin).

**Comment by ZeroExistence** [comment]
Ahh, I think I didn't explicitly said it, but we are also utilizing the `nvidia.com/gpu=<count>` resource requests and limits with our pod/job specs. So when we request 2 GPUs in the pod specs, the pod sometimes got access to 4 GPUs (GPUs set by device plugin + custom GPUs we set via `NVIDIA_VISIBLE_DEVICES`.

As far as possible, I want to utilize the `nvidia.com/gpu` resource for resource allocation tracking, and custom `NVIDIA_VISIBLE_DEVICES` for scheduling best possible combination of GPUs.

Based on the flow that you provided, we did the `NVIDIA_VISIBLE_DEVICES` envvar modification between the step 6 and 7. We overwrite the envvar from step 5, with preferred list of GPU UUIDs.

Hmm..I just can't figure how `nvidia-container-runtime-hook` still used the overwritten GPUs in the step 11.

Just another question, is it possible to blacklist GPUs, list using `NVIDIA_BLACKLIST_DEVICES`? Hmm..I checked the user guides of NVIDIA, but there seems none huh.

And I guess I will check it here, does NVIDIA device plugin consider bandwidth between GPUs, before assigning GPUs to pod level? For example, I request 3 GPUs via `nvidia.com/gpu`, and GPU-1, GPU-2, and GPU-4 has the highest bandwidth connection for 3 GPUs job, so it will be assigned to this pod.

**Comment by klueska** [comment]
> So when we request 2 GPUs in the pod specs, the pod sometimes got access to 4 GPUs (GPUs set by device plugin + custom GPUs we set via NVIDIA_VISIBLE_DEVICES.

Hmm, this is strange indeed, and knowing how the code is written, really doesn't make sense (nor have we or any of our other users ever experienced this ourselves).

> Based on the flow that you provided, we did the NVIDIA_VISIBLE_DEVICES envvar modification between the step 6 and 7. We overwrite the envvar from step 5, with preferred list of GPU UUIDs.

I'm not quite sure what you mean by you "overwrote the envvar from step 5". Where / how have you done this? If the device plugin indicates it would like to set this envvar, that will overwrite any envvars set in the pod spec or container image.

> Just another question, is it possible to blacklist GPUs, list using NVIDIA_BLACKLIST_DEVICES? Hmm..I checked the user guides of NVIDIA, but there seems none huh.

This is not currently possible.

> Does NVIDIA device plugin consider bandwidth between GPUs, before assigning GPUs to pod level? For example, I request 3 GPUs via nvidia.com/gpu, and GPU-1, GPU-2, and GPU-4 has the highest bandwidth connection for 3 GPUs job, so it will be assigned to this pod.

Yes, it will pick the combination with the highest bandwidth. It vendors in code fromm here to do so:
https://github.com/NVIDIA/go-gpuallocator/blob/main/gpuallocator/besteffort_policy.go

**Comment by ZeroExistence** [comment]
I think I found the issue. It seems that besides setting up `NVIDIA_VISIBLE_DEVICES`, device configuration was also added to the Devices spec of oci runtime, which doesn't matched the new GPUs at all.
```
Devices:[]*Device{&Device{ContainerPath:/dev/nvidia6,HostPath:/dev/nvidia6,Permissions:rw,},&Device{ContainerPath:/dev/nvidia7,HostPath:/dev/nvidia7,Permissions:rw,}
```

I will just try to overwrite/delete this device configuration, and just send an update here.

Thank you very much for the assistance!

**Comment by klueska** [comment]
Note that if you were to somehow intercept the CRI call and *add* an envvar to it for `NVIDIA_VISIBLE_DEVICES` instead of *replacing* the existing envvar, then there would be two envvars listed for `NVIDIA_VISIBLE_DEVICES` in the resulting OCI runtime spec (which is actually perfectly valid).

It's possible that the `nvidia-container-runtime-hook` would then process both of these to build out the full list of devices to inject (I'd need to double check the logic of what it is doing here).

However, `runC´would only pick one of these to actually set in your containers environment once it started (i.e. it wouldn't merge them, it would simply pick the first or last one set).

**Comment by klueska** [comment]
> I think I found the issue. It seems that besides setting up `NVIDIA_VISIBLE_DEVICES`, device configuration was also added to the Devices spec of oci runtime, which doesn't matched the new GPUs at all.

Right, this will happen if you pass the `--pass-device-specs` flag when starting the plugin as described here:
https://github.com/NVIDIA/k8s-device-plugin#configuration-option-details

**Note:** As I mentioned before, manual manipulation of the `NVIDIA_VISIBLE_DEVICES` environment is unsupported and will soon not be possible as we move to a new architecture for the `nvidia-container-toolkit` which doesn't rely on this envvar. Tegra devices already run on this new stack and server GPUs will be moving to this new stack (wihtout warning!) in the next 6-9 months.

**Comment by ZeroExistence** [comment]
Just an update on this concern, I was able to make it work by modifying the devices in the runtime container spec as well. I think this case can already be considered as close.

> Note: As I mentioned before, manual manipulation of the NVIDIA_VISIBLE_DEVICES environment is unsupported and will soon not be possible as we move to a new architecture for the nvidia-container-toolkit which doesn't rely on this envvar. Tegra devices already run on this new stack and server GPUs will be moving to this new stack (without warning!) in the next 6-9 months.

Thank you for the note. I will consider this in the future, but as of the moment, we might still stick with NVIDIA_VISIBLE_DEVICES.

Thank you very much for the assistance!

**Comment by ZeroExistence** [comment]
Closing this issue. Thank you for assistance!
