### ISSUE TITLE
Weird issue with nvidia-container-cli

### ISSUE THREAD

**Issue by ich777** [NVIDIA/nvidia-container-toolkit#29]
Hi,
nothing too urgent but maybe you have seen this before.

```
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #1:: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: device error: false: unknown device: unknown.
```

I confirmed that the UUID from the GPU and all needed parameters are passed over to the container and well the Docker daemon was also restarted to ensure that the `nvidia` runtime is available.

The issue however can be resolved if you recreate the container with the exact same parameters and seems to be running fine afterwards, never seen this before but a few users on the Unraid Forums have reported that issue now.
This issue appeared first on `Unraid 6.10.3` where `Docker 20.10.14` is the default installed version.

**Comment by klueska** [comment]
When the `nvidia-container-cli` starts up it queries NVML to enumerate all of the GPUs on the machine and caches a reference to their UUID and index (among other things). It then looks at the set of device ID passed to it and compares them against these UUIDs and indices. If there is no match, then the error above is produced.

It's unclear why it would fail with this error on one run and then succeed on the next. The run that it's failing on must error out for some reason upon trying to enumerate  all of the GPUs (even though they seem to be available), and then succeeding the next time around.

Given its transient nature, I'm wondering if it's a timeout issue. Are you running the `nvidia-persistenced` daemon on your system, or otherwise putting the GPUs into persistence mode? Without this, the response times of the GPU can be prohibitively slow and sometimes timeout.

**Comment by ich777** [comment]
@klueska thank you for that explanation and the hint with `nvidia-persistenced` will watch out for that next time it happens and recommend to disable it if they got it enabled, but until now I haven had an issue with `nvidia-persistenced` so far...

Until now I didn't heard back from the users and it seems like this was a "user" and really can't tell what was going on there.

I will close this for now and open it again if I hear back from them.
As always, thank you for your help and keep up the good work!

**Comment by ich777** [comment]
@klueska I have another report from a User with a similar issue:

```
docker: Error response from daemon: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #1: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: open failed: /proc/sys/kernel/overflowuid: permission denied: unknown. 
```

Do you might know what causes this? I don't want to reopen the issue because it seems that it only happens from time to time.
If you need any additional information please let me know.

**Comment by elezar** [comment]
@ich777 please create a new issue and provide more details on the user's system configuration? It would be good to better understand under which conditions this particular error is triggered.

**Comment by ich777** [comment]
@elezar sure thing, I will provide parts of the Diagnostics and some screenshots from the users system. The really strange part is that it works with the Plex Docker container but not with Tdarr and Unmanic. Anyways, this is something for the new Issue.
