### ISSUE TITLE
nvidia-ctk config set list still not work on 1.15.0

### ISSUE THREAD

**Issue by HaoyuWangFight** [NVIDIA/nvidia-container-toolkit#466]
I notice that this bug has been fixed on 1.15.0 rc1, but it still don't work after I install nvidia-container-toolkit 1.15.0 referencing the official guide. And I wonder if I'm using in wrong way?
```
root@ecs-bf13:~# nvidia-ctk config -i --set nvidia-container-runtime.runtimes=docker-runc,runc,crun
ERRO[0000] invalid --set option runc: invalid config option: undefined field: "runc" 
root@ecs-bf13:~# nvidia-ctk --version
NVIDIA Container Toolkit CLI version 1.15.0
commit: ddeeca392c7bd8b33d0a66400b77af7a97e16cef
```

**Comment by jocado** [comment]
Confirmed here too on `v1.15.0`, I seem to get the same error when setting a list:
```
# "${SNAP}/usr/bin/nvidia-ctk" config --in-place --set nvidia-container-runtime.mode=cdi --set nvidia-container-runtime.modes.cdi.spec-dirs="${SNAP_DATA}/etc/cdi","/var/run/cdi" --config "${SNAP_DATA}/etc/nvidia-container-runtime/config.toml"
ERRO[0000] invalid --set option /var/run/cdi: invalid config option: undefined field: "/var/run/cdi"
#
```

If I remove the second list item, so it's just a single string, item, it works:
```
# "${SNAP}/usr/bin/nvidia-ctk" config --in-place --set nvidia-container-runtime.mode=cdi --set nvidia-container-runtime.modes.cdi.spec-dirs="${SNAP_DATA}/etc/cdi" --config "${SNAP_DATA}/etc/nvidia-container-runtime/config.toml"
#
```

I have a feeling this was working at least when I last tested that too, which may of been on RC3, but I can't remember for sure.

**Comment by elezar** [comment]
I have had a look at this, and it seems as if this was caused by our update to the `urfave/cli` package that we use to construct the CLI. I think I have narrowed it down to the following PR: https://github.com/urfave/cli/issues/1238 (since the behaviour seems correct from our perspective for `v2.5.0` but no longer works for `v2.5.1`).

I will see whether there is an alternative way to specify these flags to maintain our existing behaviour.

Looking at what is available in the latest version, would using an alternative separator (e.g. `;` for the the individual runtimes) be reasonable here?

**Comment by jocado** [comment]
Thanks for taking a look :+1: 

I can't speak for anyone else, but a different separator would be fine for me.

**Comment by elezar** [comment]
@jocado I have created https://github.com/NVIDIA/nvidia-container-toolkit/pull/484 with a proposed fix.

**Comment by jocado** [comment]
@elezar Great - FYI I have tested the branch as of about 10 mins ago, using the `:` separator, and I can confirm it's working for me :+1:
