### ISSUE TITLE
amazon linux 2, aarch64 - nvidia-docker2 repo unavailable

### ISSUE THREAD

**Issue by eugeneswalker** [NVIDIA/nvidia-container-toolkit#5]
Trying to install `nvidia-docker2` package on `Amazon Linux 2` for `aarch64`, according to instructions:
https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/install-guide.html

```
...
$> distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
   && curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.repo | sudo tee /etc/yum.repos.d/nvidia-docker.repo

$> yum clean expire-cache

$> yum install nvidia-docker2
...
https://nvidia.github.io/nvidia-container-runtime/stable/amzn2/aarch64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


 One of the configured repositories failed (nvidia-container-runtime),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.
...
```

Am I doing something wrong? Is the yum repo down?

**Comment by klueska** [comment]
We recently moved to a model where all *new* packages are now hosted at:
https://nvidia.github.io/libnvidia-container/

And no longer split across the three repos of:
https://nvidia.github.io/nvidia-docker/
https://nvidia.github.io/nvidia-container-runtime/
https://nvidia.github.io/libnvidia-container/

We made sure to guarantee that all old releases would still be accessible in the old locations and that people that had `.repo` files with references to the three repos instead of one would work for all existing architectures.

However, support for `aarch64` with `amazonlinux2` is a *new* architecture/os combination that we landed support for in the same release where we made this change to a single repo. I wonder if we missed something about ensuring backwards compatibility of the repo layout for *new* architectures when users still have references to all three repos.

I can see how this might happen since there are no folders for `amazonlinux2/aarch64` in either of the `nvidia-container-runtime` or `nvidia-docker` repos.

So a quick fix would be to open up your `/etc/yum.repos.d/nvidia-docker.repo` file and remove all entries that reference `nvidia-docker` or `nvidia-container-runtime`. In the end the file should just contain:
```
[libnvidia-container]
name=libnvidia-container
baseurl=https://nvidia.github.io/libnvidia-container/stable/amzn2/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=1
gpgkey=https://nvidia.github.io/libnvidia-container/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt

[libnvidia-container-experimental]
name=libnvidia-container-experimental
baseurl=https://nvidia.github.io/libnvidia-container/experimental/amzn2/$basearch
repo_gpgcheck=1
gpgcheck=0
enabled=0
gpgkey=https://nvidia.github.io/libnvidia-container/gpgkey
sslverify=1
sslcacert=/etc/pki/tls/certs/ca-bundle.crt
```

If this is a real issue, I'm curious how we could have missed this in our testing though. It seems like it would happen with fresh installs every single time someone tried to do this.

**Comment by eugeneswalker** [comment]
That did it! Thank you for your very quick response!
