### ISSUE TITLE
Debian 12 (Bookworm) Support

### ISSUE THREAD

**Issue by JorgeO3** [NVIDIA/nvidia-container-toolkit#75]
Do you have plans to provide support for this toolkit in Debian 12, and if so, in which version will it be included?

**Comment by starryloki** [comment]
In Debian 12, it seems that using the Debian 11 toolkit works fine. I directly replaced "$distribution" with "debian11" in https://nvidia.github.io/libnvidia-container/experimental/$distribution/libnvidia-container.list, and was able to install it successfully and call the GPU within the container. This is a temporary workaround that I found useful. Nevertheless, I am still looking forward to an official update.

**Comment by benz0li** [comment]
@elezar Is it safe to use the Debian 10 (Buster) repositories with Debian 12 (Bookworm)?
❓If this is the *official way*, when are Debian 12 packages going to be symlinked (redirected) the  to `debian10`?

Similar issue: https://github.com/NVIDIA/nvidia-container-toolkit/issues/72

**Comment by benz0li** [comment]
@JorgeO3 Please reopen this issue until Debian 12 packages are officially symlinked (redirected) to `debian10`.

**Comment by elezar** [comment]
From a package perspective there should be no difference between the `debian10` packages and those for `debian12` and we would provide the package through a symlink. With that said, there may be other issues related to `debian12` support. I have seen reports that newer kernel versions break our mechanism for cgroupv2 support in the NVIDIA Container Library (`libnvidia-container1`).

Here the medium to long term solution would be to move to using the Container Device Interface (CDI) to request devices when running containers. The functionality should largely be there for all supported platforms, but the UX still needs to be improved.

**Comment by benz0li** [comment]
Currently shown at https://nvidia.github.io/libnvidia-container/stable/debian12/nvidia-container-toolkit.list:

--- snip ---
# Unsupported distribution or misconfigured repository settings

If you are seeing this message, it may mean that your are using an [unsupported distribution](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#linux-distributions).

It may also mean that your repositories are incorrectly configured.

In order to simplify the release process for the NVIDIA Container Toolkit and its components, we rely on a set of reference repositories which can be used across a number of distributions. The main references repositories and their compatible distributions are (this is not a complete list):

[...]

## Debian package repository

### Compatible with

debian10, debian11

### Repository List

[https://nvidia.github.io/libnvidia-container/stable/${distribution}/nvidia-container-toolkit.list](https://nvidia.github.io/libnvidia-container/stable/debian10/nvidia-container-toolkit.list) Note: This repository will only be active starting with the NVIDIA Container Toolkit 1.14.0 release
[https://nvidia.github.io/libnvidia-container/experimental/${distribution}/nvidia-container-toolkit.list](https://nvidia.github.io/libnvidia-container/stable/debian10/nvidia-container-toolkit.list)

Where ${distribution} is one of the compatible distributions.

### Repository URIs

https://nvidia.github.io/libnvidia-container/stable/debian10
https://nvidia.github.io/libnvidia-container/experimental/debian10
--- snip ---

Please add official support for Debian 12 with the NVIDIA Container Toolkit 1.14.0 release.

Thank you!

**Comment by benz0li** [comment]
> Here the medium to long term solution would be to move to using the Container Device Interface (CDI) to request devices when running containers. The functionality should largely be there for all supported platforms, but the UX still needs to be improved.

@elezar Agreed. But only Debian 12 has a recent enough [official] version of Podman to make use of the Container Device Interface (CDI).

**Comment by aohan237** [comment]
need this, vote for it

**Comment by elezar** [comment]
Hi all. With the release of the NVIDIA Container Toolkit, we publish our packages to a unified debian repository. We have also updated the instructions on our [documentation page](https://docs.nvidia.com/datacenter/cloud-native/container-toolkit/latest/install-guide.html#installing-with-apt). The TL;DR being that the following repolist can be used on all platforms that use debian packages:

```
https://nvidia.github.io/libnvidia-container/stable/deb/nvidia-container-toolkit.list
```
