### ISSUE TITLE
Lvmpipe rendering when switching user in docker container

### ISSUE THREAD

**Issue by asabaini** [NVIDIA/nvidia-container-toolkit#93]
Hello everyone,
We are using a container based service called KASM for our users to run remote desktop sessions on our cluster. We are currently experimenting with Ubuntu 20.04 and 22.04. KASM requires its default users - either kasm-user or root - to run the container for its inner-workings.

We were able to integrate our AD login by adding a `su` command in one of the scripts run in the container ENTRYPOINT - something to the effect of `su $OUR_AD_USER -c "script_that_starts_the_session.sh`. Everything seems to be working fine, except that we are loosing gpu passthrough. Without our AD integration, `glxinfo -B` shows our GPU as rendered. Instead, after switching user, `glxinfo -B` shows `lvmpipe` - CPU based rendering.

We don't really have much control over which flags we can pass to `docker run`, which would allow us to use something like `docker run -u $OUR_AD_USER ...`. Do you have any suggestions on how to switch user within a container without loosing GPU?

I appreciate any insight or help anyone can share with me
Best,
Alberto

**Comment by elezar** [comment]
Hi @asabaini. Do you mean to say without the user switch things work as expected?

This is unexpected. It may be that the environment for the user is not set up correctly to access the GPUs. Please confirm that the same NVIDIA libraries (e.g. `libcuda.so`and the `libnvidia*` libraries) are in the ld.cache when using the switched user.

Uncommenting the `debug = ` lines in the `/etc/nvidia-container-runtime/config.toml` file should generate some log files which could indicate whether there are differences in the injection. I would not expect this to be the case, since the changes are made to the container environment before the container is started as a prestart hook.

Just for information, which version of the NVIDIA Container Toolkit are you using?

**Comment by asabaini** [comment]
Hello @elezar,
> Do you mean to say without the user switch things work as expected?
Yes it works as expected

> This is unexpected. It may be that the environment for the user is not set up correctly to access the GPUs.
Thank you for this suggestion. I'll take a look at our setup and see if indeed we are improperly setting up the environment

I'll get back to you as soon as possible
Thanks again
Alberto

**Comment by asabaini** [comment]
Hello @elezar, 
Indeed we were missing some environment variables and there was a permission issue with the user for `/dev/dri/renderDXXX`.

Thank you for your help
Best
Alberto
